### ISSUE TITLE
Plugin Crashes On Startup

### ISSUE THREAD

**Issue by RegExe** [viktor-ferenczi/conveyor-optimizer#3]
Loading the plugin and simply starting torch throws the following error (from logs)

`14:39:45.3704 [FATAL]  Initializer: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ConveyorOptimizer.Patches.MyGridConveyorSystemPatch' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47
   --- End of inner exception stack trace ---
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch.Patch(PatchContext ctx) in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 78
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Managers.PatchManager.PatchManager.AddPatchShim(Type type) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Managers\PatchManager\PatchManager.cs:line 54
   at Torch.Managers.PatchManager.PatchManager.AddPatchShims(Assembly asm) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Managers\PatchManager\PatchManager.cs:line 24
   at Torch.TorchBase.RegisterAuxAssembly(Assembly asm) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 492
   at Torch.Managers.PluginManager.RegisterAllAssemblies(IReadOnlyCollection`1 assemblies) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 437
   at Torch.Managers.PluginManager.LoadPlugin(PluginItem item) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 411
   at Torch.Managers.PluginManager.LoadPlugins() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 197
   at Torch.TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 339
   at Torch.Server.TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 144
   at Torch.Server.Initializer.<Run>b__23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\Initializer.cs:line 153
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ConveyorOptimizer.Patches.MyGridConveyorSystemPatch' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47
   --- End of inner exception stack trace ---
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch.Patch(PatchContext ctx) in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 78
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Managers.PatchManager.PatchManager.AddPatchShim(Type type) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Managers\PatchManager\PatchManager.cs:line 54
   at Torch.Managers.PatchManager.PatchManager.AddPatchShims(Assembly asm) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Managers\PatchManager\PatchManager.cs:line 24
   at Torch.TorchBase.RegisterAuxAssembly(Assembly asm) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 492
   at Torch.Managers.PluginManager.RegisterAllAssemblies(IReadOnlyCollection`1 assemblies) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 437
   at Torch.Managers.PluginManager.LoadPlugin(PluginItem item) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 411
   at Torch.Managers.PluginManager.LoadPlugins() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Plugins\PluginManager.cs:line 197
   at Torch.TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 339
   at Torch.Server.TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 144
   at Torch.Server.Initializer.<Run>b__23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\Initializer.cs:line 153
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
14:39:45.3863 [FATAL]  Initializer: System.TypeInitializationException: The type initializer for 'ConveyorOptimizer.Patches.MyGridConveyorSystemPatch' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47
   --- End of inner exception stack trace ---
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch.Patch(PatchContext ctx) in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 78
System.TypeInitializationException: The type initializer for 'ConveyorOptimizer.Patches.MyGridConveyorSystemPatch' threw an exception. ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47
   --- End of inner exception stack trace ---
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch.Patch(PatchContext ctx) in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 78
14:39:45.3863 [FATAL]  Initializer: System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at ConveyorOptimizer.Patches.MyGridConveyorSystemPatch..cctor() in C:\Dev\conveyor-optimizer\ConveyorOptimizer\Patches\MyGridConveyorSystemPatch.cs:line 47`

**Comment by viktor-ferenczi** [comment]
Based on my initial tests after the recent major game update this plugin is not required anymore. 

Please switch to the [Performance Improvements](https://github.com/viktor-ferenczi/performance-improvements) plugin instead: https://torchapi.com/plugins/view/?guid=c2cf3ed2-c6ac-4dbd-ab9a-613a1ef67784

I'm going to update the Readme of this GitHub page with the above.
